
name: Docker Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
  

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: gpu
            dockerfile: docker/Dockerfile
            platforms: linux/amd64
            flavor: ""
            tags: |
              type=semver,pattern={{version}},value=${{ github.event.release.tag_name }}
              type=semver,pattern={{major}}.{{minor}},value=${{ github.event.release.tag_name }}
              type=raw,value=latest

          - id: cpu
            dockerfile: docker/Dockerfile-cpu
            platforms: linux/amd64,linux/arm64
            flavor: |
              suffix=-cpu
            tags: |
              type=semver,pattern={{version}},value=${{ github.event.release.tag_name }}
              type=semver,pattern={{major}}.{{minor}},value=${{ github.event.release.tag_name }}
              type=raw,value=latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract assets
        run: |
          mkdir assets
          gh release download ${{ github.event.release.tag_name }} \
            --repo ${{ github.repository }} \
            --pattern "assets.tar.gz"

          tar -xzf assets.tar.gz -C assets
          rm assets.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        if: matrix.id == 'cpu'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: ${{ matrix.flavor }}
          tags: ${{ matrix.tags }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: ${{ matrix.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.id }}
          cache-to: type=gha,mode=max,scope=${{ matrix.id }}

